"""Unit tests for the OpenAI-compatible LLM provider."""

from unittest.mock import MagicMock, patch

from app.infrastructure.config.settings import Settings
from app.infrastructure.llm.openai import OpenAILLMProvider


@patch("app.infrastructure.llm.openai.ChatOpenAI")
def test_provider_uses_configured_settings(
    mock_chat_openai: MagicMock,
) -> None:
    """Initialize ChatOpenAI with application settings."""
    settings = Settings(
        openai_api_key="test-api-key",
        openai_base_url="https://proxy.example/v1",
        chat_model="test-chat-model",
    )

    OpenAILLMProvider(settings)

    mock_chat_openai.assert_called_once_with(
        model="test-chat-model",
        api_key="test-api-key",
        base_url="https://proxy.example/v1",
        temperature=0,
    )


@patch("app.infrastructure.llm.openai.ChatOpenAI")
def test_generate_returns_response_content(
    mock_chat_openai: MagicMock,
) -> None:
    """Return the content generated by ChatOpenAI."""
    response = MagicMock()
    response.content = "Тестовый ответ."
    mock_chat_openai.return_value.invoke.return_value = response

    settings = Settings(openai_api_key="test-api-key")
    provider = OpenAILLMProvider(settings)

    result = provider.generate(
        query="Как оформить отпуск?",
        context="Отпуск оформляется через HR-систему.",
    )

    assert result == "Тестовый ответ."


def test_provider_requires_api_key() -> None:
    """Reject provider initialization without an API key."""
    settings = Settings(openai_api_key="")

    try:
        OpenAILLMProvider(settings)
    except ValueError as exc:
        assert str(exc) == "OPENAI_API_KEY is required for RAG."
    else:
        raise AssertionError("Expected ValueError.")
